CREATE TABLE recipes (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    renditions TEXT NOT NULL,
    total_time_tier TEXT,
    seo_title TEXT NOT NULL,
    video_id TEXT,
    instructions TEXT,
    draft_status TEXT NOT NULL,
    thumbnail_alt_text TEXT NOT NULL,
    credits TEXT NOT NULL,
    promotion TEXT NOT NULL,
    facebook_posts TEXT NOT NULL,
    brand TEXT,
    show TEXT,
    is_one_top INTEGER NOT NULL,
    total_time_minutes INTEGER,
    servings_noun_plural TEXT NOT NULL,
    is_shoppable INTEGER NOT NULL,
    price TEXT,
    show_id INTEGER NOT NULL,
    buzz_id TEXT,
    tips_and_ratings_enabled INTEGER NOT NULL,
    video_url TEXT,
    approved_at INTEGER NOT NULL,
    nutrition_visibility TEXT NOT NULL,
    servings_noun_singular TEXT NOT NULL,
    name TEXT,
    created_at INTEGER NOT NULL,
    sections TEXT,
    compilations TEXT NOT NULL,
    beauty_url TEXT,
    original_video_url TEXT,
    country TEXT NOT NULL,
    keywords TEXT NOT NULL,
    seo_path TEXT,
    prep_time_minutes INTEGER,
    cook_time_minutes INTEGER,
    description TEXT,
    inspired_by_url TEXT,
    topics TEXT NOT NULL,
    video_ad_content TEXT,
    language TEXT NOT NULL,
    user_ratings TEXT,
    brand_id TEXT,
    tags TEXT NOT NULL,
    canonical_id TEXT NOT NULL,
    slug TEXT NOT NULL,
    nutrition TEXT,
    thumbnail_url TEXT,
    yields TEXT NOT NULL,
    recipe_api_id INTEGER NOT NULL,
    num_servings INTEGER NOT NULL,
    aspect_ratio TEXT NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    setting_key TEXT NOT NULL,
    setting_value TEXT NOT NULL
);

INSERT INTO settings (setting_key, setting_value)
VALUES 
    ('results_per_page', '10'),
    ('max_results', '50'),
    ('units', 'metric');